our @MON = ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec');
$lang{TASK} = 'Task';
$lang{TASKS} = 'Tasks';
$lang{ADD_TASK} = 'Add task';
$lang{CHANGE_TASK} = 'Change task';
$lang{MY_TASKS} = 'My tasks';
$lang{TASKS_LIST} = 'Tasks list';
$lang{TASKS_TYPE} = 'Tasks types';
$lang{TASK_TYPE} = 'Task type';
$lang{TASK_NAME} = 'Task name';
$lang{TASK_DESCRIBE} = 'Task describe';
$lang{PLAN_DATE} = 'Scheduled date';
$lang{CONTROL_DATE} = 'Control date';
$lang{CONTROL_TIME} = 'Control time';
$lang{DAYS_N} = 'days';
$lang{WEEKS} = 'weeks';
$lang{TASK_TYPE_ADDED} = "New type added.";
$lang{TASK_TYPE_ERROR} = "Error creating type";
$lang{UNFULFILLED_TASKS} = "Unfulfilled tasks";
$lang{COMPLETED_TASKS} = "Completed tasks";
$lang{TASK_IN_WORK} = "In work";
$lang{TASK_IN_QUEUE} = "In queue";

1;