$lang{TASK} = 'Задача';
$lang{TASKS} = 'Задачі';
$lang{ADD_TASK} = 'Додати задачу';
$lang{CHANGE_TASK} = 'Змінити задачу';
$lang{MY_TASKS} = 'МоЇ задачі';
$lang{TASKS_LIST} = 'Список задач';
$lang{TASKS_TYPE} = 'Типи задач';
$lang{TASK_TYPE} = 'Тип задачі';
$lang{TASK_NAME} = 'Назва задачі';
$lang{TASK_DESCRIBE} = 'Опис задачі';
$lang{PLAN_DATE} = 'Запланована дата';
$lang{CONTROL_DATE} = 'Контрольна дата';
$lang{CONTROL_TIME} = 'Контрольний термін';
$lang{DAYS_N} = 'Дні';
$lang{WEEKS} = 'Тиждня';
$lang{TASK_TYPE_ADDED} = "Новий тип задачі додано.";
$lang{TASK_TYPE_ERROR} = "Помилка створення нового типу задач.";
$lang{UNFULFILLED_TASKS} = "Невиконані задачі";
$lang{COMPLETED_TASKS} = "Виконані задачі";
$lang{TASK_IN_WORK} = "В роботі";
$lang{TASK_IN_QUEUE} = "В черзі";

1;
